### PR TITLE
Fix facebook button initialization

### LINKED ISSUE #19: Facebook share button doesn't always show up
It looks like a turbolinks issue.  The button will sometimes not show up until you refresh the page.

To reproduce:
1. Create a ride
2. Go to a ride list page, such as my rides
3. Navigate back to the ride, the share button won't show up

### PR DESCRIPTION
**Pull request by yashdavisgupta**
Resolves #19

### CODE REVIEW

**Comment by yashdavisgupta** [comment]
The major issue is solved, for whatever reason styling still doesn't work.

**Comment by yashdavisgupta** [comment]
Now this is ready.

File: app/assets/javascripts/init-elements.js [hunk 1]
```diff
@@ -1,3 +1,65 @@
...
+      }
+      if (!Facebook.eventsBound) {
+        return Facebook.bindEvents();
+      }
+    }
+  };
+
+  Facebook.bindEvents = function() {
+    if (typeof Turbolinks !== 'undefined' && Turbolinks.supported) {
+      $(document).on('page:fetch', Facebook.saveRoot).on('page:change', Facebook.restoreRoot).on('page:load', function() {
```
Comment (AlexanderOtavka) [inline app/assets/javascripts/init-elements.js]: Where did jQuery come from?

File: app/assets/javascripts/init-elements.js [hunk 2]
```diff
@@ -1,3 +1,65 @@
+this.Facebook = (function() {
+  var eventsBound, rootElement;
+
+  function Facebook() {}
+
+  rootElement = null;
+
+  eventsBound = false;
+
+  Facebook.load = function() {
```
Comment (AlexanderOtavka) [inline app/assets/javascripts/init-elements.js]: It looks like we are manually creating the facebook api scripts.  Is there a better way to do this?  Can't we mark the scripts already in the dom so that turbolinks knows to reload them?

File: app/assets/javascripts/init-elements.js [hunk 3]
```diff
@@ -1,3 +1,65 @@
...
+    }
+    return Facebook.eventsBound = true;
+  };
+
+  Facebook.saveRoot = function() {
+    return Facebook.rootElement = document.getElementById('fb-root').detach();
+  };
+
+  Facebook.restoreRoot = function() {
+    if (document.getElementById('fb-root').length > 0) {
```
Comment (AlexanderOtavka) [inline app/assets/javascripts/init-elements.js]: What is the length property?  `getElementById` returns a singular element or `null`

File: app/assets/javascripts/init-elements.js [hunk 4]
```diff
@@ -1,3 +1,65 @@
...
+      return document.getElementById('fb-root').replaceWith(Facebook.rootElement);
+    } else {
+      return document.body.append(Facebook.rootElement);
+    }
+  };
+
+  Facebook.appId = function() {
+    return '2479083255670794';
```
Comment (AlexanderOtavka) [inline app/assets/javascripts/init-elements.js]: We shouldn't duplicate this.  Grab it from the meta tag instead.

File: app/views/rides/_share_ride.html.erb [hunk 5]
```diff
@@ -15,8 +15,9 @@
         data-layout="button" data-size="large">
       <a target="_blank"
          href="https://www.facebook.com/sharer/sharer.php?u=<%= url_encode share_ride_url(ride) %>&amp;src=sdkpreparse"
-         class="fb-xfbml-parse-ignore">
-        Share
+         class="btn waves-effect" style="background: #1877f2">
+         <i class="large material-icons">thumb_up</i>
```
Comment (AlexanderOtavka) [inline app/views/rides/_share_ride.html.erb]: Can we put facebook branding here instead?  I want it to be clear we are sharing to facebook

File: app/assets/javascripts/init-elements.js [hunk 6]
```diff
@@ -1,3 +1,65 @@
...
+  };
+
+  return Facebook;
+
+})();
+
+Facebook.load();
```
Comment (AlexanderOtavka) [inline app/assets/javascripts/init-elements.js]: When does this get called?

File: app/assets/javascripts/init-elements.js [hunk 7]
```diff
@@ -1,3 +1,65 @@
...
+  function Facebook() {}
+
+  rootElement = null;
+
+  eventsBound = false;
+
+  Facebook.load = function() {
+    if(document.getElementById('fb-root')){
+      var facebookScript, firstScript, initialRoot;
+      if (!(document.getElementById('fb-root').size() > 0)) {
```
[the remark this answers is not in the document]
Comment (AlexanderOtavka) [reply app/assets/javascripts/init-elements.js]: It kinda seems like residual code from jQuery
